name: Bug Report
description: Report a bug you encountered while using AI Services.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much context as possible to help us resolve the issue you encountered.
  - type: textarea
    attributes:
      label: Bug Description
      description: Please describe clearly and concisely what the bug is.
      placeholder: |
        What happened? What did you expect to happen? Code examples can be helpful if available.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps on how to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Please share information about your environment, such as project version, PHP version, and operating system.
      placeholder: |
        - AI Services version:
        - PHP version:
        - Other relevant information:
    validations:
      required: false
